services:

  # Eclipse Mosquitto MQTT Broker
  mosquitto:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - MOSQUITTO_VERSION=${MOSQUITTO_VERSION:-latest}
    environment:
      - MOSQUITTO_USERNAME=${MOSQUITTO_USERNAME}
      - MOSQUITTO_PASSWORD=${MOSQUITTO_PASSWORD}
    image: eclipse-mosquitto:${MOSQUITTO_VERSION:-latest}
    container_name: mosquitto
    restart: always
    networks:
      - mti-network
    volumes:
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log
    ports:
      - ${MOSQUITTO_PORT}:${MOSQUITTO_PORT}

  telegraf:
    container_name: telegraf
    image: telegraf:${TELEGRAF_VERSION}
    depends_on:
      influxdb:
        condition: service_healthy
    environment:
      - TZ=${TELEGRAF_TIMEZONE}
      - MOSQUITTO_USERNAME=${MOSQUITTO_USERNAME}
      - MOSQUITTO_PASSWORD=${MOSQUITTO_PASSWORD}
    networks:
      - mti-network
    volumes:
      - ./telegraf/telegraf.conf:/etc/telegraf/telegraf.conf:ro
  
  influxdb:
    container_name: influxdb
    image : influxdb:${INFLUXDB_VERSION}
    healthcheck:
      test: "curl -f http://influxdb:8086/health"
      interval: 3s
      timeout: 10s
      retries: 5
    environment:
      - TZ=Europe/Bucharest
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=${INFLUXDB_USERNAME}
      - DOCKER_INFLUXDB_INIT_PASSWORD=${INFLUXDB_PASSWORD}
      - DOCKER_INFLUXDB_INIT_ORG=${ORGANISATION}
      - DOCKER_INFLUXDB_INIT_BUCKET=${ORGANISATION}
      - DOCKER_INFLUXDB_INIT_RETENTION=1w
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=${INFLUXDB_ADMIN_TOKEN}
    volumes:
      - ./influxdb/config:/etc/influxdb2
      - ./influxdb/data:/var/lib/influxdb2
    ports:
      - ${INFLUXDB_PORT}:${INFLUXDB_PORT}
    networks:
      - mti-network

networks:
  mti-network:
      name: mti-network
